### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by marvinmai** [marvinmai/ChatApplication#3]
- [ ] für den Server ein gui erstellen, ggf. erweitern
     - [ ] mit IP des Servers, start- und shutdown-button
     - [ ] ggf. Feld für Adminpassword

- [ ] Adminfunktionen implementieren
    - [ ] login als Admin über befehl (bspw. "server admin >passwort<")mit im Server hinterlegtem Passwort
        -> hinterlegt im Server für entspr. Client admin-eigenschaft
    - [ ] Kicken von usern über befehl, server kick >username<

- [ ] Anschreiben eines einzigen Users über Befehl
    - [ ] Implementieren der Unterklasse " PrivateMessage"
    - [ ] Befehl integrieren, bspw "@>username< >message<"

- [ ] Klassendesign kontrollieren, ggf überarbeiten
